Update SpawnersListener.java
[00:30:01 ERROR]: Could not pass event BlockPlaceEvent to WildStacker v2025.1-b148
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.EntityType.name()" because "spawnerType" is null
        at WildStacker-2025.1-b148.jar/com.bgsoftware.wildstacker.listeners.SpawnersListener.finishSpawnerPlace(SpawnersListener.java:325) ~[WildStacker-2025.1-b148.jar:?]
        at WildStacker-2025.1-b148.jar/com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:301) ~[WildStacker-2025.1-b148.jar:?]